// flow-typed signature: 3df5dcddc602953a7b425410f7d55c53
// flow-typed version: <<STUB>>/babel_v^5.4.7/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel/bin/babel-external-helpers' {
  declare module.exports: any;
}

declare module 'babel/bin/babel-node' {
  declare module.exports: any;
}

declare module 'babel/bin/babel-plugin' {
  declare module.exports: any;
}

declare module 'babel/bin/babel' {
  declare module.exports: any;
}

declare module 'babel/lib/_babel-node' {
  declare module.exports: any;
}

declare module 'babel/lib/babel-external-helpers' {
  declare module.exports: any;
}

declare module 'babel/lib/babel-node' {
  declare module.exports: any;
}

declare module 'babel/lib/babel-plugin/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel-plugin/templates/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/dir' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/file' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/util' {
  declare module.exports: any;
}

declare module 'babel/polyfill' {
  declare module.exports: any;
}

declare module 'babel/register-without-polyfill' {
  declare module.exports: any;
}

declare module 'babel/register' {
  declare module.exports: any;
}

declare module 'babel/src/_babel-node' {
  declare module.exports: any;
}

declare module 'babel/src/babel-external-helpers' {
  declare module.exports: any;
}

declare module 'babel/src/babel-node' {
  declare module.exports: any;
}

declare module 'babel/src/babel-plugin/index' {
  declare module.exports: any;
}

declare module 'babel/src/babel-plugin/templates/index' {
  declare module.exports: any;
}

declare module 'babel/src/babel/dir' {
  declare module.exports: any;
}

declare module 'babel/src/babel/file' {
  declare module.exports: any;
}

declare module 'babel/src/babel/index' {
  declare module.exports: any;
}

declare module 'babel/src/babel/util' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel-node/directory/in-files/foo/index' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel-node/filename/in-files/bar' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel-node/require/in-files/bar2' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel-node/require/in-files/foo2' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel-node/require/in-files/not_node_modules' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/--ignore/in-files/src/bar/index' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/--ignore/in-files/src/foo/foo' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/--ignore/out-files/lib/bar/index' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/--only/in-files/src/bar/index' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/--only/in-files/src/foo/index' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/--only/out-files/lib/bar/index' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps inline/in-files/src/bar/bar' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps inline/in-files/src/foo' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/bar/bar' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/foo' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps/in-files/src/bar/bar' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps/in-files/src/foo' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/bar/bar' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/foo' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir/in-files/src/bar/bar' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir/in-files/src/foo' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir/out-files/lib/bar/bar' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/dir --out-dir/out-files/lib/foo' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filename --out-file --source-maps inline/in-files/script' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filename --out-file --source-maps inline/out-files/script2' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filename --out-file/in-files/script' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filename --out-file/out-files/script2' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps inline/in-files/script' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps inline/in-files/script2' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps inline/out-files/script3' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps/in-files/script' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps/in-files/script2' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps/out-files/script3' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file/in-files/script' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file/in-files/script2' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/filenames --out-file/out-files/script3' {
  declare module.exports: any;
}

declare module 'babel/test/fixtures/babel/stdin --out-file/out-files/script' {
  declare module.exports: any;
}

declare module 'babel/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel/bin/babel-external-helpers.js' {
  declare module.exports: $Exports<'babel/bin/babel-external-helpers'>;
}
declare module 'babel/bin/babel-node.js' {
  declare module.exports: $Exports<'babel/bin/babel-node'>;
}
declare module 'babel/bin/babel-plugin.js' {
  declare module.exports: $Exports<'babel/bin/babel-plugin'>;
}
declare module 'babel/bin/babel.js' {
  declare module.exports: $Exports<'babel/bin/babel'>;
}
declare module 'babel/index' {
  declare module.exports: $Exports<'babel'>;
}
declare module 'babel/index.js' {
  declare module.exports: $Exports<'babel'>;
}
declare module 'babel/lib/_babel-node.js' {
  declare module.exports: $Exports<'babel/lib/_babel-node'>;
}
declare module 'babel/lib/babel-external-helpers.js' {
  declare module.exports: $Exports<'babel/lib/babel-external-helpers'>;
}
declare module 'babel/lib/babel-node.js' {
  declare module.exports: $Exports<'babel/lib/babel-node'>;
}
declare module 'babel/lib/babel-plugin/index.js' {
  declare module.exports: $Exports<'babel/lib/babel-plugin/index'>;
}
declare module 'babel/lib/babel-plugin/templates/index.js' {
  declare module.exports: $Exports<'babel/lib/babel-plugin/templates/index'>;
}
declare module 'babel/lib/babel/dir.js' {
  declare module.exports: $Exports<'babel/lib/babel/dir'>;
}
declare module 'babel/lib/babel/file.js' {
  declare module.exports: $Exports<'babel/lib/babel/file'>;
}
declare module 'babel/lib/babel/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/index'>;
}
declare module 'babel/lib/babel/util.js' {
  declare module.exports: $Exports<'babel/lib/babel/util'>;
}
declare module 'babel/polyfill.js' {
  declare module.exports: $Exports<'babel/polyfill'>;
}
declare module 'babel/register-without-polyfill.js' {
  declare module.exports: $Exports<'babel/register-without-polyfill'>;
}
declare module 'babel/register.js' {
  declare module.exports: $Exports<'babel/register'>;
}
declare module 'babel/src/_babel-node.js' {
  declare module.exports: $Exports<'babel/src/_babel-node'>;
}
declare module 'babel/src/babel-external-helpers.js' {
  declare module.exports: $Exports<'babel/src/babel-external-helpers'>;
}
declare module 'babel/src/babel-node.js' {
  declare module.exports: $Exports<'babel/src/babel-node'>;
}
declare module 'babel/src/babel-plugin/index.js' {
  declare module.exports: $Exports<'babel/src/babel-plugin/index'>;
}
declare module 'babel/src/babel-plugin/templates/index.js' {
  declare module.exports: $Exports<'babel/src/babel-plugin/templates/index'>;
}
declare module 'babel/src/babel/dir.js' {
  declare module.exports: $Exports<'babel/src/babel/dir'>;
}
declare module 'babel/src/babel/file.js' {
  declare module.exports: $Exports<'babel/src/babel/file'>;
}
declare module 'babel/src/babel/index.js' {
  declare module.exports: $Exports<'babel/src/babel/index'>;
}
declare module 'babel/src/babel/util.js' {
  declare module.exports: $Exports<'babel/src/babel/util'>;
}
declare module 'babel/test/fixtures/babel-node/directory/in-files/foo/index.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel-node/directory/in-files/foo/index'>;
}
declare module 'babel/test/fixtures/babel-node/filename/in-files/bar.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel-node/filename/in-files/bar'>;
}
declare module 'babel/test/fixtures/babel-node/require/in-files/bar2.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel-node/require/in-files/bar2'>;
}
declare module 'babel/test/fixtures/babel-node/require/in-files/foo2.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel-node/require/in-files/foo2'>;
}
declare module 'babel/test/fixtures/babel-node/require/in-files/not_node_modules.jsx' {
  declare module.exports: $Exports<'babel/test/fixtures/babel-node/require/in-files/not_node_modules'>;
}
declare module 'babel/test/fixtures/babel/--ignore/in-files/src/bar/index.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/--ignore/in-files/src/bar/index'>;
}
declare module 'babel/test/fixtures/babel/--ignore/in-files/src/foo/foo.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/--ignore/in-files/src/foo/foo'>;
}
declare module 'babel/test/fixtures/babel/--ignore/out-files/lib/bar/index.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/--ignore/out-files/lib/bar/index'>;
}
declare module 'babel/test/fixtures/babel/--only/in-files/src/bar/index.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/--only/in-files/src/bar/index'>;
}
declare module 'babel/test/fixtures/babel/--only/in-files/src/foo/index.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/--only/in-files/src/foo/index'>;
}
declare module 'babel/test/fixtures/babel/--only/out-files/lib/bar/index.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/--only/out-files/lib/bar/index'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps inline/in-files/src/bar/bar.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir --source-maps inline/in-files/src/bar/bar'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps inline/in-files/src/foo.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir --source-maps inline/in-files/src/foo'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/bar/bar.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/bar/bar'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/foo.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/foo'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps/in-files/src/bar/bar.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir --source-maps/in-files/src/bar/bar'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps/in-files/src/foo.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir --source-maps/in-files/src/foo'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/bar/bar.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/bar/bar'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/foo.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/foo'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir/in-files/src/bar/bar.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir/in-files/src/bar/bar'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir/in-files/src/foo.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir/in-files/src/foo'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir/out-files/lib/bar/bar.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir/out-files/lib/bar/bar'>;
}
declare module 'babel/test/fixtures/babel/dir --out-dir/out-files/lib/foo.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/dir --out-dir/out-files/lib/foo'>;
}
declare module 'babel/test/fixtures/babel/filename --out-file --source-maps inline/in-files/script.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filename --out-file --source-maps inline/in-files/script'>;
}
declare module 'babel/test/fixtures/babel/filename --out-file --source-maps inline/out-files/script2.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filename --out-file --source-maps inline/out-files/script2'>;
}
declare module 'babel/test/fixtures/babel/filename --out-file/in-files/script.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filename --out-file/in-files/script'>;
}
declare module 'babel/test/fixtures/babel/filename --out-file/out-files/script2.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filename --out-file/out-files/script2'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps inline/in-files/script.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file --source-maps inline/in-files/script'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps inline/in-files/script2.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file --source-maps inline/in-files/script2'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps inline/out-files/script3.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file --source-maps inline/out-files/script3'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps/in-files/script.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file --source-maps/in-files/script'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps/in-files/script2.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file --source-maps/in-files/script2'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file --source-maps/out-files/script3.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file --source-maps/out-files/script3'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file/in-files/script.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file/in-files/script'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file/in-files/script2.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file/in-files/script2'>;
}
declare module 'babel/test/fixtures/babel/filenames --out-file/out-files/script3.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/filenames --out-file/out-files/script3'>;
}
declare module 'babel/test/fixtures/babel/stdin --out-file/out-files/script.js' {
  declare module.exports: $Exports<'babel/test/fixtures/babel/stdin --out-file/out-files/script'>;
}
declare module 'babel/test/index.js' {
  declare module.exports: $Exports<'babel/test/index'>;
}
