// flow-typed signature: 07999ce58d2072df9aa98985c7382479
// flow-typed version: <<STUB>>/hamjest-spy_v^2.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hamjest-spy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hamjest-spy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hamjest-spy/lib/index' {
  declare module.exports: any;
}

declare module 'hamjest-spy/lib/matcher' {
  declare module.exports: any;
}

declare module 'hamjest-spy/lib/spy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hamjest-spy/lib/index.js' {
  declare module.exports: $Exports<'hamjest-spy/lib/index'>;
}
declare module 'hamjest-spy/lib/matcher.js' {
  declare module.exports: $Exports<'hamjest-spy/lib/matcher'>;
}
declare module 'hamjest-spy/lib/spy.js' {
  declare module.exports: $Exports<'hamjest-spy/lib/spy'>;
}
