// flow-typed signature: c6b96ff20c57e6c9e71212313bfa7b5b
// flow-typed version: <<STUB>>/hamjest_v^3.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hamjest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hamjest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hamjest/dist/hamjest' {
  declare module.exports: any;
}

declare module 'hamjest/dist/hamjest.min' {
  declare module.exports: any;
}

declare module 'hamjest/gulpfile' {
  declare module.exports: any;
}

declare module 'hamjest/lib/assertThat' {
  declare module.exports: any;
}

declare module 'hamjest/lib/Description' {
  declare module.exports: any;
}

declare module 'hamjest/lib/fail' {
  declare module.exports: any;
}

declare module 'hamjest/lib/fixErrorJson' {
  declare module.exports: any;
}

declare module 'hamjest/lib/hamjest' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/AllOf' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/AnyOf' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/DateComparisonMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/Every' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/failsToMatch' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/falsy' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/FeatureMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/hasDescription' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/hasExactlyOneItem' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/hasSize' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/inRange' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/Is' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsAnything' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsArray' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsArrayContaining' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsArrayContainingInAnyOrder' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsArrayOrderedBy' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsArrayWithItem' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsArrayWithItems' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsBoolean' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsCloseTo' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsDate' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsDefined' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/isEmpty' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsEqual' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsFulfilled' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsFunction' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsFunctionThrowing' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsInstanceOf' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsNot' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsNumber' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsObject' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsObjectWithProperties' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsPromise' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsRegExp' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsRejected' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsSame' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsString' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/IsStringMatching' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/Matcher' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/matches' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/NumberComparisonMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/promiseAgnostic' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/returns' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/SubstringMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/truthy' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/typedError' {
  declare module.exports: any;
}

declare module 'hamjest/lib/matchers/TypeSafeMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/lib/promiseThat' {
  declare module.exports: any;
}

declare module 'hamjest/lib/utils/acceptingMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/lib/utils/asMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/lib/utils/getType' {
  declare module.exports: any;
}

declare module 'hamjest/lib/utils/getTypeName' {
  declare module.exports: any;
}

declare module 'hamjest/test/browser/hamjestSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/assertThatSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/deferMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/DescriptionSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/failSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/hamjestSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/AllOfSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/AnyOfSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/DateComparisonMatcherSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/EverySpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/failsToMatchSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/falsySpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/FeatureMatcherSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/hasDescriptionSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/hasExactlyOneItemSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/hasSizeSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/inRangeSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsArrayContainingInAnyOrderSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsArrayContainingSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsArrayOrderedBySpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsArraySpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsArrayWithItemSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsArrayWithItemsSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsBooleanSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsCloseToSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsDateSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsDefinedSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/isEmptySpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsEqualSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsFulfilledSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsFunctionSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsFunctionThrowingSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsInstanceOfSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsNotSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsNumberSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsObjectSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsObjectWithPropertiesSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsPromiseSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsRegExpSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsRejectedSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsSameSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsStringMatchingSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/IsStringSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/MatcherSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/matchesSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/NumberComparisonMatcherSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/returnsSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/SubstringMatcherSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/truthySpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/typedErrorSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/matchers/TypeSafeMatcherSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/promiseThatSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/TestMatcher' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/utils/acceptingMatcherSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/utils/asMatcherSpec' {
  declare module.exports: any;
}

declare module 'hamjest/test/node/zoo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hamjest/dist/hamjest.js' {
  declare module.exports: $Exports<'hamjest/dist/hamjest'>;
}
declare module 'hamjest/dist/hamjest.min.js' {
  declare module.exports: $Exports<'hamjest/dist/hamjest.min'>;
}
declare module 'hamjest/gulpfile.js' {
  declare module.exports: $Exports<'hamjest/gulpfile'>;
}
declare module 'hamjest/index' {
  declare module.exports: $Exports<'hamjest'>;
}
declare module 'hamjest/index.js' {
  declare module.exports: $Exports<'hamjest'>;
}
declare module 'hamjest/lib/assertThat.js' {
  declare module.exports: $Exports<'hamjest/lib/assertThat'>;
}
declare module 'hamjest/lib/Description.js' {
  declare module.exports: $Exports<'hamjest/lib/Description'>;
}
declare module 'hamjest/lib/fail.js' {
  declare module.exports: $Exports<'hamjest/lib/fail'>;
}
declare module 'hamjest/lib/fixErrorJson.js' {
  declare module.exports: $Exports<'hamjest/lib/fixErrorJson'>;
}
declare module 'hamjest/lib/hamjest.js' {
  declare module.exports: $Exports<'hamjest/lib/hamjest'>;
}
declare module 'hamjest/lib/matchers/AllOf.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/AllOf'>;
}
declare module 'hamjest/lib/matchers/AnyOf.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/AnyOf'>;
}
declare module 'hamjest/lib/matchers/DateComparisonMatcher.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/DateComparisonMatcher'>;
}
declare module 'hamjest/lib/matchers/Every.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/Every'>;
}
declare module 'hamjest/lib/matchers/failsToMatch.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/failsToMatch'>;
}
declare module 'hamjest/lib/matchers/falsy.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/falsy'>;
}
declare module 'hamjest/lib/matchers/FeatureMatcher.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/FeatureMatcher'>;
}
declare module 'hamjest/lib/matchers/hasDescription.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/hasDescription'>;
}
declare module 'hamjest/lib/matchers/hasExactlyOneItem.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/hasExactlyOneItem'>;
}
declare module 'hamjest/lib/matchers/hasSize.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/hasSize'>;
}
declare module 'hamjest/lib/matchers/inRange.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/inRange'>;
}
declare module 'hamjest/lib/matchers/Is.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/Is'>;
}
declare module 'hamjest/lib/matchers/IsAnything.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsAnything'>;
}
declare module 'hamjest/lib/matchers/IsArray.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsArray'>;
}
declare module 'hamjest/lib/matchers/IsArrayContaining.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsArrayContaining'>;
}
declare module 'hamjest/lib/matchers/IsArrayContainingInAnyOrder.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsArrayContainingInAnyOrder'>;
}
declare module 'hamjest/lib/matchers/IsArrayOrderedBy.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsArrayOrderedBy'>;
}
declare module 'hamjest/lib/matchers/IsArrayWithItem.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsArrayWithItem'>;
}
declare module 'hamjest/lib/matchers/IsArrayWithItems.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsArrayWithItems'>;
}
declare module 'hamjest/lib/matchers/IsBoolean.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsBoolean'>;
}
declare module 'hamjest/lib/matchers/IsCloseTo.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsCloseTo'>;
}
declare module 'hamjest/lib/matchers/IsDate.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsDate'>;
}
declare module 'hamjest/lib/matchers/IsDefined.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsDefined'>;
}
declare module 'hamjest/lib/matchers/isEmpty.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/isEmpty'>;
}
declare module 'hamjest/lib/matchers/IsEqual.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsEqual'>;
}
declare module 'hamjest/lib/matchers/IsFulfilled.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsFulfilled'>;
}
declare module 'hamjest/lib/matchers/IsFunction.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsFunction'>;
}
declare module 'hamjest/lib/matchers/IsFunctionThrowing.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsFunctionThrowing'>;
}
declare module 'hamjest/lib/matchers/IsInstanceOf.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsInstanceOf'>;
}
declare module 'hamjest/lib/matchers/IsNot.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsNot'>;
}
declare module 'hamjest/lib/matchers/IsNumber.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsNumber'>;
}
declare module 'hamjest/lib/matchers/IsObject.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsObject'>;
}
declare module 'hamjest/lib/matchers/IsObjectWithProperties.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsObjectWithProperties'>;
}
declare module 'hamjest/lib/matchers/IsPromise.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsPromise'>;
}
declare module 'hamjest/lib/matchers/IsRegExp.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsRegExp'>;
}
declare module 'hamjest/lib/matchers/IsRejected.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsRejected'>;
}
declare module 'hamjest/lib/matchers/IsSame.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsSame'>;
}
declare module 'hamjest/lib/matchers/IsString.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsString'>;
}
declare module 'hamjest/lib/matchers/IsStringMatching.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/IsStringMatching'>;
}
declare module 'hamjest/lib/matchers/Matcher.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/Matcher'>;
}
declare module 'hamjest/lib/matchers/matches.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/matches'>;
}
declare module 'hamjest/lib/matchers/NumberComparisonMatcher.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/NumberComparisonMatcher'>;
}
declare module 'hamjest/lib/matchers/promiseAgnostic.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/promiseAgnostic'>;
}
declare module 'hamjest/lib/matchers/returns.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/returns'>;
}
declare module 'hamjest/lib/matchers/SubstringMatcher.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/SubstringMatcher'>;
}
declare module 'hamjest/lib/matchers/truthy.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/truthy'>;
}
declare module 'hamjest/lib/matchers/typedError.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/typedError'>;
}
declare module 'hamjest/lib/matchers/TypeSafeMatcher.js' {
  declare module.exports: $Exports<'hamjest/lib/matchers/TypeSafeMatcher'>;
}
declare module 'hamjest/lib/promiseThat.js' {
  declare module.exports: $Exports<'hamjest/lib/promiseThat'>;
}
declare module 'hamjest/lib/utils/acceptingMatcher.js' {
  declare module.exports: $Exports<'hamjest/lib/utils/acceptingMatcher'>;
}
declare module 'hamjest/lib/utils/asMatcher.js' {
  declare module.exports: $Exports<'hamjest/lib/utils/asMatcher'>;
}
declare module 'hamjest/lib/utils/getType.js' {
  declare module.exports: $Exports<'hamjest/lib/utils/getType'>;
}
declare module 'hamjest/lib/utils/getTypeName.js' {
  declare module.exports: $Exports<'hamjest/lib/utils/getTypeName'>;
}
declare module 'hamjest/test/browser/hamjestSpec.js' {
  declare module.exports: $Exports<'hamjest/test/browser/hamjestSpec'>;
}
declare module 'hamjest/test/node/assertThatSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/assertThatSpec'>;
}
declare module 'hamjest/test/node/deferMatcher.js' {
  declare module.exports: $Exports<'hamjest/test/node/deferMatcher'>;
}
declare module 'hamjest/test/node/DescriptionSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/DescriptionSpec'>;
}
declare module 'hamjest/test/node/failSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/failSpec'>;
}
declare module 'hamjest/test/node/hamjestSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/hamjestSpec'>;
}
declare module 'hamjest/test/node/matchers/AllOfSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/AllOfSpec'>;
}
declare module 'hamjest/test/node/matchers/AnyOfSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/AnyOfSpec'>;
}
declare module 'hamjest/test/node/matchers/DateComparisonMatcherSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/DateComparisonMatcherSpec'>;
}
declare module 'hamjest/test/node/matchers/EverySpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/EverySpec'>;
}
declare module 'hamjest/test/node/matchers/failsToMatchSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/failsToMatchSpec'>;
}
declare module 'hamjest/test/node/matchers/falsySpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/falsySpec'>;
}
declare module 'hamjest/test/node/matchers/FeatureMatcherSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/FeatureMatcherSpec'>;
}
declare module 'hamjest/test/node/matchers/hasDescriptionSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/hasDescriptionSpec'>;
}
declare module 'hamjest/test/node/matchers/hasExactlyOneItemSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/hasExactlyOneItemSpec'>;
}
declare module 'hamjest/test/node/matchers/hasSizeSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/hasSizeSpec'>;
}
declare module 'hamjest/test/node/matchers/inRangeSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/inRangeSpec'>;
}
declare module 'hamjest/test/node/matchers/IsArrayContainingInAnyOrderSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsArrayContainingInAnyOrderSpec'>;
}
declare module 'hamjest/test/node/matchers/IsArrayContainingSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsArrayContainingSpec'>;
}
declare module 'hamjest/test/node/matchers/IsArrayOrderedBySpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsArrayOrderedBySpec'>;
}
declare module 'hamjest/test/node/matchers/IsArraySpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsArraySpec'>;
}
declare module 'hamjest/test/node/matchers/IsArrayWithItemSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsArrayWithItemSpec'>;
}
declare module 'hamjest/test/node/matchers/IsArrayWithItemsSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsArrayWithItemsSpec'>;
}
declare module 'hamjest/test/node/matchers/IsBooleanSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsBooleanSpec'>;
}
declare module 'hamjest/test/node/matchers/IsCloseToSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsCloseToSpec'>;
}
declare module 'hamjest/test/node/matchers/IsDateSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsDateSpec'>;
}
declare module 'hamjest/test/node/matchers/IsDefinedSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsDefinedSpec'>;
}
declare module 'hamjest/test/node/matchers/isEmptySpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/isEmptySpec'>;
}
declare module 'hamjest/test/node/matchers/IsEqualSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsEqualSpec'>;
}
declare module 'hamjest/test/node/matchers/IsFulfilledSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsFulfilledSpec'>;
}
declare module 'hamjest/test/node/matchers/IsFunctionSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsFunctionSpec'>;
}
declare module 'hamjest/test/node/matchers/IsFunctionThrowingSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsFunctionThrowingSpec'>;
}
declare module 'hamjest/test/node/matchers/IsInstanceOfSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsInstanceOfSpec'>;
}
declare module 'hamjest/test/node/matchers/IsNotSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsNotSpec'>;
}
declare module 'hamjest/test/node/matchers/IsNumberSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsNumberSpec'>;
}
declare module 'hamjest/test/node/matchers/IsObjectSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsObjectSpec'>;
}
declare module 'hamjest/test/node/matchers/IsObjectWithPropertiesSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsObjectWithPropertiesSpec'>;
}
declare module 'hamjest/test/node/matchers/IsPromiseSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsPromiseSpec'>;
}
declare module 'hamjest/test/node/matchers/IsRegExpSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsRegExpSpec'>;
}
declare module 'hamjest/test/node/matchers/IsRejectedSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsRejectedSpec'>;
}
declare module 'hamjest/test/node/matchers/IsSameSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsSameSpec'>;
}
declare module 'hamjest/test/node/matchers/IsSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsSpec'>;
}
declare module 'hamjest/test/node/matchers/IsStringMatchingSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsStringMatchingSpec'>;
}
declare module 'hamjest/test/node/matchers/IsStringSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/IsStringSpec'>;
}
declare module 'hamjest/test/node/matchers/MatcherSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/MatcherSpec'>;
}
declare module 'hamjest/test/node/matchers/matchesSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/matchesSpec'>;
}
declare module 'hamjest/test/node/matchers/NumberComparisonMatcherSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/NumberComparisonMatcherSpec'>;
}
declare module 'hamjest/test/node/matchers/returnsSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/returnsSpec'>;
}
declare module 'hamjest/test/node/matchers/SubstringMatcherSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/SubstringMatcherSpec'>;
}
declare module 'hamjest/test/node/matchers/truthySpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/truthySpec'>;
}
declare module 'hamjest/test/node/matchers/typedErrorSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/typedErrorSpec'>;
}
declare module 'hamjest/test/node/matchers/TypeSafeMatcherSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/matchers/TypeSafeMatcherSpec'>;
}
declare module 'hamjest/test/node/promiseThatSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/promiseThatSpec'>;
}
declare module 'hamjest/test/node/TestMatcher.js' {
  declare module.exports: $Exports<'hamjest/test/node/TestMatcher'>;
}
declare module 'hamjest/test/node/utils/acceptingMatcherSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/utils/acceptingMatcherSpec'>;
}
declare module 'hamjest/test/node/utils/asMatcherSpec.js' {
  declare module.exports: $Exports<'hamjest/test/node/utils/asMatcherSpec'>;
}
declare module 'hamjest/test/node/zoo.js' {
  declare module.exports: $Exports<'hamjest/test/node/zoo'>;
}
